### ISSUE TITLE
EditorView context is not just the editor view

### ISSUE THREAD

**Issue by tilgovi** [nytimes/react-prosemirror#10]
I'd like to propose changing `EditorViewContext` to simply `EditorContext`.

It must have both `view` and `state` because `view.state` is not always equal to `state`. We should recognize that the context is more than just the view and rename it.

**Comment by SMores** [comment]
Agreed that we should rename it! If we land on `Editor` in #8, then agreed on `EditorContext`. Basically I'm just saying "let's use the same namespacing everywhere" which is probably so uncontroversial that I don't need to bother saying it haha

**Comment by tilgovi** [comment]
Maybe. I broke them up because the hooks actually receive the view as an argument while this context has both a view and a state in its value. I could imagine renaming this `EditorContext` without renaming those, but not vice versa.

**Comment by SMores** [comment]
Closed by #13
