### ISSUE TITLE
The current logo have some issue, so I made a new one, how do you think about it?

### ISSUE THREAD

**Issue by caocanx** [nytimes/react-prosemirror#119]
**The issue**

![Frame 118](https://github.com/nytimes/react-prosemirror/assets/15025287/0a7854fa-9c90-45a1-bece-fc132032ca87)

**Old vs New(light mode)**

![Frame 115](https://github.com/nytimes/react-prosemirror/assets/15025287/1661e891-9865-46f9-b401-aeabc6dd617a)

**Old vs New(dark mode)**

![Frame 117](https://github.com/nytimes/react-prosemirror/assets/15025287/f72e7554-5c3b-4997-9acb-d813f0c3c544)

**Comment by smoores-dev** [comment]
❤️ ❤️ ❤️ 

I literally made the current logo on my phone while on vacation. This is both adorable and much cleaner. If you want to open a PR to swap them out, I would definitely approve!

**Comment by smoores-dev** [comment]
#120

**Comment by annabialas** [comment]
i lol'ed at this PR title when i saw a notification about it in slack. it's so cute.
