### ISSUE TITLE
Release Request: 0.7.0-next.8

### ISSUE THREAD

**Issue by smoores-dev** [nytimes/react-prosemirror#131]
Hey folks! e2f94b393fd9adaf591ae473890fe00689ca4851 includes a small bug fix for `0.7.0-next.7`; could we get a new release for that whenever someone has a chance? Thanks!

**Comment by smoores-dev** [comment]
Tagging @tilgovi and @saranrapjs; I don't know if anyone else has permission to make a release!

**Comment by saranrapjs** [comment]
It looks like on `react-editor-view`, we haven't been committing `0.7.0-next`-patterned version updates on the branch. Before I attempt to release `0.7.0-next.8`, is there any reason I shouldn't commit/push/track the prerelease versions on that branch?

**Comment by tilgovi** [comment]
I haven't thought about whether to commit and tag the pre-releases there.

I guess part of my hesitation has been around whether we'd need to actually release a v0.7 that doesn't include merging the react-editor-view branch, and unsure how to handle that.

**Comment by smoores-dev** [comment]
Hmmm... why would it matter?

**Comment by tilgovi** [comment]
Maybe it's too late at this point, but I guess what I should have done is suggested a different tag other than `next`?

**Comment by smoores-dev** [comment]
Ah, yeah that's fair haha. It's already tagged as `next` on npm, so I don't know that tagging it on GitHub really makes much of a difference

**Comment by tilgovi** [comment]
Well, I done it. Should I keep the ticket open to talk about automating prereleases or documenting the release process, or open separate tickets?

**Comment by saranrapjs** [comment]
I'd love to document the release process, but happy to open a distinct issue for that (it looks like you didn't commit prerelease versions onto the branch, but did publish to npm?)
