### ISSUE TITLE
`selectNode` doesn't exist on inline image node when applying mark

### ISSUE THREAD

**Issue by qwertyquest** [nytimes/react-prosemirror#143]
This is related to the `react-editor-view` branch. Loving it so far, by the way, and appreciate all the work you've done @smoores-dev!

If we set a `NodeSelection` on an image node and attempt to apply a mark, we get the following error: `Uncaught TypeError: desc.selectNode is not a function`

The error appears to occur on [line 106](https://github.com/nytimes/react-prosemirror/blob/aa1dfeedc54a99c20ec154e4e9e2b4ed1782cb8e/src/selection/selectionToDOM.ts#L106) of `selectionToDOM.ts`.

Our image node `schema` is defined as:

```
{
    attrs: {
        alt: { default: null },
        src: {},
        title: { default: null },
    },
    draggable: true,
    group: "inline",
    inline: true,
    parseDOM: [
        {
            getAttrs(dom: Node | string): {
                alt: string | null;
                src: string | null;
                title: string | null;
            } {
                return {
                    alt: (dom as HTMLElement).getAttribute("alt"),
                    src: (dom as HTMLElement).getAttribute("src"),
                    title: (dom as HTMLElement).getAttribute("title"),
                };
            },
            tag: "img[src]",
        },
    ],
    toDOM(node: ProseMirrorNode): DOMOutputSpec {
        return ["img", node.attrs];
    },
}
```

Not sure if the fix is as easy as conditionally checking for `selectNode` before calling (or what else that would break).

**Comment by smoores-dev** [comment]
Hi @qwertyquest, thanks for the report! Incidentally, I actually think that this is fixed in the latest commit to `react-editor-view`, which hasn't been released yet. You should be able to specify the version in your `package.json` as `github:nytimes/react-prosemirror#3fc9d12cf432d621dbf365818f7a9db1d3ae6a76` to get the latest, though; would you give that a shot and let me know whether it fixes your issue? That includes some other improvements to the react-editor-view branch as well.

One thing to note when upgrading there is that the `pos: number` prop has been replaced with a `getPos: () => number` prop. If you're using that anywhere you'll need to update your usage!

**Comment by qwertyquest** [comment]
Looks like the bug appears to be in both the latest release and the latest commit version. When running the latest commit version, the stack trace mentions the error occurs in the `<ProseMirrorInner>` component.

![react-prosemirror-errors](https://github.com/user-attachments/assets/ee7987e4-ad7a-49f4-9cc9-130481108600)

**Comment by qwertyquest** [comment]
Huh, so it looks like setting `selectable: false` in the image node schema fixes the error. Makes me wonder if it's related to the usage of [isSelectable]https://prosemirror.net/docs/ref/#state.NodeSelection^isSelectable somewhere?

**Comment by qwertyquest** [comment]
Sorry, deleted my last comment (was incorrect about the potential fix).

Seems to be happening with both bold and italic marks. Bold mark schema is:

```
{
    parseDOM: [
        { tag: "b" },
        { tag: "strong" },
        {
            getAttrs: (value) =>
                /^(bold(er)?|[5-9]\d{2,})$/u.test(value) && null,
            style: "font-weight",
        },
    ],
    toDOM(): DOMOutputSpec {
        return ["strong"];
    },
}
```

Mark keymap function:

```
const markType = proseMirrorSchema.marks[this.proseMirrorMarkName()];
return {
    "Mod-b": toggleMark(markType),
    "Mod-B": toggleMark(markType),
};
```

**Comment by smoores-dev** [comment]
Thanks, I'm able to reproduce now! This ended up being a pretty simple fix; I had even left a TODO comment for myself suggesting that this may have been broken haha.

The latest commit on the `next-built` branch (`86a73c1035ddf617b5c528d14e7e2696076c0177`) should resolve the issue!
