### ISSUE TITLE
Focus ProseMirror on mount

### ISSUE THREAD

**Issue by vangberg** [nytimes/react-prosemirror#146]
Hi

Is there any way to access the `EditorView` instance from the component that renders the `ProseMirrror` instance? I want to focus the editor when a component property changes by calling `view.focus()`.

Thanks!

**Comment by smoores-dev** [comment]
@vangberg is it alright to close this?

**Comment by vangberg** [comment]
Yeah. For future reference, I created an `AutoFocus` component, which is just concerned with focusing the view:

```tsx
# AutoFocus.tsx
import { useEditorEffect } from "@nytimes/react-prosemirror";
import React from "react";

export const AutoFocus: React.FC = () => {
    useEditorEffect((view) => {
        view.dom.focus();
    }, []);

    return null;
};
```

This component is then rendered is a child of the `ProseMirror` compoent:

```tsx
<ProseMirror …>
  <AutoFocus />
  …
</ProseMirror>
```
