### ISSUE TITLE
Using subclasses of EditorView

### ISSUE THREAD

**Issue by abingham** [nytimes/react-prosemirror#31]
My project uses a subclass of `EditorView`, and I'm exploring whether we can also use `react-prosemirror`. What's the best way to get `react-prosemirror` to use my subclass? It looks like I can probably create my own version of `useEditorView`, plug that into `EditorProvider`, and things will be ok. Will this work, or is there some reason I shouldn't do this?

Even if this works, is there a simpler way? This feels really long-winded just to use an alternative view. 

If there's no other way, would it be possible improve support for view sublasses? Maybe the `ProseMirror` component could have a prop for constructing the `EditorView` or something along those lines.

**Comment by SMores** [comment]
I honestly didn't know that anyone _was_ subclassing `EditorView`! Can you speak more to your use case for doing so? This library is definitely designed to use the base `prosemirror-*` packages right now, so you're right that it would be challenging to use it for this case in its current (still nascent!) form.

**Comment by abingham** [comment]
We override the `dispatch()` method to adjust transactions a bit. I think we could (and perhaps should!) do the same work with a plugin now, but I think that wasn't possible when we initially implemented this behavior. So I'm not sure if my case is particularly motivating, but it doesn't seem unreasonable to subclass EditorView in general.

**Comment by SMores** [comment]
So ProseMirror (and the ProseMirror component) supports passing a custom `dispatchTransaction` function that will be called in place of the default EditorView.dispatch (you can see examples of this in the README for this project, in fact!). Dos that support your use case, or are you describing something different? I am actually a bit hesitant to support subclassing the EditorView; it's behavior is so customizable that I would rather push folks toward the proper interfaces (plugins, custom dispatch, etc) for customization than support arbitrary subclassing (which could conceivably result in broken behavior, if the subclasses violate any of our assumptions about how the EditorView works!)

**Comment by abingham** [comment]
Yes, what you've got already looks like it'll work for me. Thanks for helping me sort through this!
