### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by brunozampirom** [nytimes/react-prosemirror#39]
I would like to know if the library supports React Native.

I don't think so, as it looks like it has a dependency on react-dom.

```
Unable to resolve "react-dom" from "node_modules/@nytimes/react-prosemirror/dist/cjs/hooks/useEditorView.js"
```

If not, do you know and recommend any prosemirror editor in RN?

Thanks! 😁

**Comment by asp3** [comment]
https://github.com/iamcco/jsdom-jscore-rn

would some `jsdom` subsitution like this library potentially solve the issue of needing a web view?

**Comment by tilgovi** [comment]
I don't know. I would be surprised if that works. It's probably better to use something other than ProseMirror, something native to the platform, or embed a full web view.
