### ISSUE TITLE
Editor props are not flat

### ISSUE THREAD

**Issue by tilgovi** [nytimes/react-prosemirror#7]
We currently have `editorProps` and `editorState`, but I think we should flatten things so that `<ProseMirror>` just takes `{ mount: HTMLElement } & DirectEditorProps`. That is closer to the ProseMirror API. They are separate only as a result of the existing props that were used in internal code that spawned this project, but there's no reason I can see to keep it that way.

**Comment by SMores** [comment]
This is done already, no? https://github.com/nytimes/react-prosemirror/blob/main/src/components/ProseMirrorInner.tsx#LL7-L11C3

**Comment by tilgovi** [comment]
Is the documentation just wrong? https://github.com/nytimes/react-prosemirror#prosemirror

**Comment by tilgovi** [comment]
Yup. Documentation is just wrong. Want to re-open this, or should I open a separate ticket?
