### ISSUE TITLE
`prosemirror-gapcursor` doesn't work yet

### ISSUE THREAD

**Issue by konstantinmuenster** [nytimes/react-prosemirror#79]
Hey @smoores-dev, I noticed that ProseMirror's gap cursor plugin doesn't work out-of-the-box.

It might be due to `Decoration.widget`, which is [internally used](https://github.com/ProseMirror/prosemirror-gapcursor/blob/master/src/index.ts#L90). At least, I recall that Alex mentioned something about widget support isn't fully there yet.

I am not 100% sure if this is the actual root cause. Would be great to have your feedback on how easily it could be fixed. Having the gap cursor back in place is not a critical requirement for the first draft, but it would be important to restore the functionality eventually.

**Comment by smoores-dev** [comment]
This is resolved by #115 !
