### ISSUE TITLE
Deferred layout effects are poorly named

### ISSUE THREAD

**Issue by tilgovi** [nytimes/react-prosemirror#9]
I still find "deferred" to be non-obvious naming. While it's true that using `useDeferredLayoutEffect` registers an effect that runs later than `useLayoutEffect`, it doesn't say anything about when "later" is.

I've been thinking for a while that `<LayoutGroup />` and `useLayoutGroupEffect` might make more sense. The `<LayoutGroup />` components creates a boundary in which layout effects can be grouped together and processed after all the children of the group have run their layout effects by way of `useLayoutGroupEffect`.

**Comment by tilgovi** [comment]
Thinking about this in the context of ProseMirror, what we want is to run all editor effects together _as a group_ once the editor view's state is up to date.

**Comment by SMores** [comment]
I think I've finally come around on this one. Not sure why now, exactly, but part of it is that I had definitely been reading the hook name as `useLayoutEffectGroup` (no idea if that's how it was previously being written) before, and I think `useLayoutGroupEffect` is much less confusing.
